version: '3'

tasks:
  run:
    cmds:
      - bend run src/main.bend -s
    desc: Run the main.bend file
      
  runc:
    cmds:
      - bend run-c src/main.bend -s
    desc: Run the main.bend file parallelly
  
  lib-gen:
    cmds:
      - mkdir -p src/gen && cat src/lib/*.bend > src/gen/merged_lib.bend && echo "Merged lib files in src/gen/merged_lib.bend"
    desc: 
      Generate a merged lib file from all the lib files in /src/lib

  benchmark:
    cmds: 
      - 'sh scripts/benchmark.sh false'
    desc: 
      Run the benchmark on the convolution [64, 128, 256, 512, 1024]

  benchmark-par:
    cmds: 
      - 'sh scripts/benchmark.sh true'
    desc:
      Run the benchmark on the convolution with parallel algorithm [64, 128, 256, 512, 1024]